# Generated by Django 3.0.8 on 2020-08-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='students',
        ),
    ]
