# Generated by Django 3.0.8 on 2020-08-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200801_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='students2',
        ),
    ]
